/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csci2320;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Random;
import java.util.Scanner;
import java.util.Set;

public class App {
    record SetListPair(TrieSet set, List<String> list) {}

    public static void main(String[] args) {
        try (Scanner sc = new Scanner(System.in)) {
            long seed = sc.nextLong();
            Random rand = new Random(seed);
            int size = sc.nextInt();
            var slp = buildSet(rand, size);
            TrieSet set = slp.set;
            List<String> words = slp.list;
            String type = sc.next();
            switch(type) {
                case "contains":
                    contains(rand, set, words);
                    break;
                case "remove":
                    remove(rand, set, words);
                    break;
                case "iterator":
                    iterator(rand, set, words);
                    break;
                case "prefix":
                    prefix(rand, set, words);
                    break;
                case "suffix":
                    suffix(rand, set, words);
                    break;
            }
        }
    }

    static String randomString(Random rand, int len) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < len; ++i) {
            sb.append((char)('a'+rand.nextInt(6)));
        }
        return sb.toString();
    }

    static SetListPair buildSet(Random rand, int size) {
        TrieSet set = new TrieSet();
        List<String> list = new ArrayList<>();
        for (int i = 0; i < size; ++i) {
            String str = randomString(rand, 8);
            while (set.contains(str)) str = randomString(rand, 5 + rand.nextInt(4));
            set.add(str);
            list.add(str);
        }
        return new SetListPair(set, list);
    }
    
    static void contains(Random rand, TrieSet set, List<String> words) {
        for (var word: words) {
            if (!set.contains(word)) {
                System.out.println("Didn't find " + word);
                return;
            }
        }
        for (int i = 0; i < 10; ++i) {
            String newWord = randomString(rand, 5 + rand.nextInt(4));
            while (words.contains(newWord)) {
                newWord = randomString(rand, 5 + rand.nextInt(4));
            }
            if (set.contains(newWord)) {
                System.out.println("Found " + newWord + " that isn't there.");
            }
        }
    }

    static void remove(Random rand, TrieSet set, List<String> words) {
        List<String> removed = new ArrayList<>();
        for (var word: words) {
            if (rand.nextDouble() < 0.4) {
                if (!set.contains(word)) {
                    System.out.println("Houston, we have a problem. Can't remove word that should be there: " + word);
                    return;
                }
                removed.add(word);
                set.remove(word);
            }
        }
        for (var word: removed) {
            if (set.contains(word)) {
                System.out.println("After removal we found " + word);
            }
        }
    }

    static void iterator(Random rand, TrieSet set, List<String> words) {
        Set<String> wordSet = new HashSet<>(words);
        Set<String> trieSet = new HashSet<>();
        for (var word: set) trieSet.add(word);
        if (!wordSet.equals(trieSet)) {
            System.out.println("Iterator didn't get all values: " + words.size() + " != " + trieSet.size());
        }
        System.out.println("Iterator built set matches.");
    }

    static void prefix(Random rand, TrieSet set, List<String> words) {
        for (var word: words) {
            if (rand.nextDouble() < 0.4) {
                var newWord = word + randomString(rand, 3);
                String prefix = set.longestPrefix(newWord);
                if (!set.contains(prefix)) {
                    System.out.println("Got a prefix that isn't in the set. " + prefix);
                    return;
                }
                if (!words.contains(prefix)) {
                    System.out.println("Got a prefix that isn't in the list of words. " + prefix);
                    return;
                }
            }
        }
    }

    static void suffix(Random rand, TrieSet set, List<String> words) {
        for (int i = 0; i < words.size() / 5; ++i) {
            var word = words.get(i);
            var prefix = word.substring(0, word.length() - 3);
            var suffixes = set.validSuffixes(prefix);
            if (!suffixes.contains(word.substring(prefix.length()))) {
                System.out.println("Original not found in suffixes.");
            }
            for (var w: words) {
                if (w.startsWith(prefix)) {
                    if (!suffixes.contains(word.substring(prefix.length()))) {
                        System.out.println("Didn't get suffix of " + w + " with prefix of " + prefix);
                    }
                }
            }
        }
    }
}
